name: papeltaksi
description: Papel E-Para A.Ş. Taksi POS Uygulaması - SoftPOS ve Fiziksel POS desteği ile taksi ödeme çözümü
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Routing
  go_router: ^12.1.3

  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Security & Encryption
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0

  # QR Code & NFC
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5

  # Payment & POS
  url_launcher: ^6.2.2
  uni_links: ^0.5.1

  # Utils
  intl: ^0.18.1
  uuid: ^4.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Logging
  logger: ^2.0.2+1

  # Splash Screen
  flutter_native_splash: ^2.3.9

  # Permissions
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

