name: Build Flutter APK

on:
  push:
    branches: [ claude/taxi-payment-softpos-app-* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true

    - name: Clean Flutter build
      run: flutter clean

    - name: Get dependencies
      run: flutter pub get

    - name: Pre-build setup (generate Gradle wrapper)
      run: |
        cd android
        if [ ! -f gradlew ]; then
          echo "Generating Gradle wrapper..."
          gradle wrapper --gradle-version 8.3
        fi
        chmod +x gradlew || true
        cd ..

    - name: Analyze code
      run: flutter analyze
      continue-on-error: true

    - name: Run tests
      run: flutter test
      continue-on-error: true

    - name: Build Debug APK
      run: flutter build apk --debug --flavor dev

    - name: Build Release APK (Dev)
      run: flutter build apk --release --flavor dev

    - name: Build Release APK (Prod)
      run: flutter build apk --release --flavor prod

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-dev-debug.apk

    - name: Upload Dev Release APK
      uses: actions/upload-artifact@v4
      with:
        name: dev-release-apk
        path: build/app/outputs/flutter-apk/app-dev-release.apk

    - name: Upload Prod Release APK
      uses: actions/upload-artifact@v4
      with:
        name: prod-release-apk
        path: build/app/outputs/flutter-apk/app-prod-release.apk

    - name: Create Release Summary
      run: |
        echo "## Build Successful! 🎉" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### APK Files Generated:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Debug APK (Dev flavor)" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Release APK (Dev flavor)" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Release APK (Prod flavor)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Download artifacts from the Actions tab above!" >> $GITHUB_STEP_SUMMARY
